#pragma once
#define VERSION_MAJOR 0
#define VERSION_MINOR 2
#define VERSION_BUILD 1
#define VERSION_REVISION 1


#define STRINGIZE2(s) #s
#define STRINGIZE(s) STRINGIZE2(s)
#define VER_FILE_VERSION VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD, VERSION_REVISION
#define VER_FILE_VERSION_STR STRINGIZE(VERSION_MAJOR)		\
							 "." STRINGIZE(VERSION_MINOR)	\
							 "." STRINGIZE(VERSION_BUILD)	\
							 "." STRINGIZE(VERSION_REVISION)
